In [2]:
import numpy as np

H = np.matrix([[1, 1, 0, 1, 1, 0, 0, 1, 0, 0],\
              [0, 1, 1, 0, 1, 1, 1, 0 ,0 ,0],\
              [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],\
              [1, 1, 0, 0, 0, 1, 1, 0, 1, 0],\
              [0, 0, 1, 0, 0, 1, 0, 1, 0, 1]])

In [6]:
u = np.random.randint(0, 2, (10,1))
u

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0]])

In [7]:
s = (H * u) % 2
s

matrix([[0],
        [0],
        [1],
        [0],
        [1]])

In [9]:
s.T * H

matrix([[0, 0, 1, 1, 0, 1, 0, 2, 1, 2]])

In [10]:
np.concatenate((H, s), 1)

matrix([[1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0],
        [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1],
        [1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1]])

In [11]:
np.sum(H, 0)

matrix([[2, 3, 2, 2, 2, 3, 2, 3, 2, 2]])

In [30]:
s.T * H / np.sum(H, 0)

matrix([[0.5       , 0.33333333, 0.5       , 1.        , 0.5       ,
         0.33333333, 0.        , 1.        , 0.5       , 1.        ]])

In [31]:
error = np.zeros(u.shape)
error[np.argmax(s.T * H)] = 1

In [37]:
H * (u - error) % 2

matrix([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])